/**
 * Renders every brand raster from source: the favicon set from
 * `public/brand/mark.svg`, and one social card per language.
 *
 *   pnpm tsx scripts/build-brand.ts
 *
 * The social cards are drawn as SVG and rasterised rather than generated by an
 * image model. Cards are mostly type — the wordmark, a tagline and the domain —
 * and image models cannot set type. Drawing them keeps the letterforms sharp,
 * the palette exactly on the site's tokens, and the file under 100 KB.
 *
 * Rasterising goes through CairoSVG in the system Python rather than adding
 * sharp or a headless browser: the Worker size ceiling makes every dependency
 * a real cost, and this only ever runs at author time.
 */
import { execFile } from "node:child_process";
import { writeFile } from "node:fs/promises";
import { promisify } from "node:util";

const run = promisify(execFile);

const PAPER = "#f7f4ed";
const INK = "#241f1a";
const COPPER = "#c0561d";
const RULE = "#ddd6c8";
const MUTED = "#6b6055";

/** The mark, inlined so the card is a single self-contained document. */
const MARK = (x: number, y: number, s: number) => `
  <g transform="translate(${x} ${y}) scale(${s / 64})">
    <rect width="64" height="64" fill="${INK}"/>
    <path d="M0 58h64v6H0z" fill="${COPPER}"/>
    <g fill="${PAPER}">
      <path d="M27.5 16.5v6.4L18.4 32l9.1 9.1v6.4L12 32z"/>
      <path d="M36.5 16.5 52 32 36.5 47.5v-8.9a6.6 6.6 0 0 1 0-13.2z"/>
    </g>
  </g>`;

type Card = {
  file: string;
  font: string;
  headline: string[];
  eyebrow: string;
  headlineSize: number;
  lineHeight: number;
};

const CARDS: Card[] = [
  {
    file: "public/og-cover.jpg",
    font: "Helvetica Neue, Helvetica, Arial, sans-serif",
    eyebrow: "INDEPENDENT DIRECTORY · FREE, NO SIGN-UP",
    headline: ["DeepSeek Harness plugins,", "one command away."],
    headlineSize: 72,
    lineHeight: 86,
  },
  {
    file: "public/og-cover-zh.jpg",
    font: "PingFang SC, Hiragino Sans GB, Helvetica, sans-serif",
    eyebrow: "DSH 插件独立索引站 · 免费，免注册",
    headline: ["DeepSeek Harness 插件，", "一行命令装好。"],
    headlineSize: 66,
    lineHeight: 92,
  },
];

function card(c: Card) {
  const lines = c.headline
    .map(
      (line, i) =>
        `<text x="80" y="${300 + i * c.lineHeight}" font-family="${c.font}" font-size="${c.headlineSize}" font-weight="700" fill="${i === c.headline.length - 1 ? COPPER : INK}" letter-spacing="-1">${line}</text>`,
    )
    .join("\n    ");

  return `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630" viewBox="0 0 1200 630">
    <rect width="1200" height="630" fill="${PAPER}"/>

    <!-- Foundry rules: a measured grid, the same device the site uses. -->
    <g stroke="${RULE}" stroke-width="1">
      <line x1="80" y1="150" x2="1120" y2="150"/>
      <line x1="80" y1="470" x2="1120" y2="470"/>
    </g>

    ${MARK(80, 64, 64)}
    <text x="164" y="112" font-family="${c.font}" font-size="34" font-weight="700" fill="${INK}" letter-spacing="-0.6">DSH Marketplace</text>

    <text x="80" y="200" font-family="${c.font}" font-size="19" font-weight="600" fill="${MUTED}" letter-spacing="2">${c.eyebrow}</text>

    ${lines}

    <rect x="80" y="524" width="60" height="6" fill="${COPPER}"/>
    <text x="80" y="574" font-family="ui-monospace, Menlo, monospace" font-size="24" fill="${MUTED}">dshmarketplace.dev</text>
  </svg>`;
}

const ICONS_PY = `
import cairosvg, io, struct, os
src = "public/brand/mark.svg"

for out, s in {
    "public/brand/icon-192.png": 192,
    "public/brand/icon-512.png": 512,
    "public/brand/apple-touch-icon.png": 180,
}.items():
    cairosvg.svg2png(url=src, write_to=out, output_width=s, output_height=s)
    print(f"  {out} ({os.path.getsize(out)} bytes)")

# 16/32/48 are the frames Windows and older Safari actually select.
frames = []
for s in (16, 32, 48):
    buf = io.BytesIO()
    cairosvg.svg2png(url=src, write_to=buf, output_width=s, output_height=s)
    frames.append((s, buf.getvalue()))

header = struct.pack("<HHH", 0, 1, len(frames))
entries, blobs, offset = b"", b"", 6 + 16 * len(frames)
for s, data in frames:
    entries += struct.pack("<BBBBHHII", s, s, 0, 0, 1, 32, len(data), offset)
    blobs += data
    offset += len(data)

with open("public/favicon.ico", "wb") as f:
    f.write(header + entries + blobs)
print(f"  public/favicon.ico ({os.path.getsize('public/favicon.ico')} bytes, {len(frames)} frames)")
`;

async function main() {
  try {
    await run("python3", ["-c", "import cairosvg"]);
  } catch {
    console.error("cairosvg is not installed — run: pip3 install cairosvg");
    process.exit(1);
  }

  console.log("icons from public/brand/mark.svg:");
  console.log((await run("python3", ["-c", ICONS_PY])).stdout.trimEnd());

  console.log("social cards:");
  for (const c of CARDS) {
    const svgPath = `/tmp/${c.file.split("/").pop()}.svg`;
    const png = svgPath.replace(/\.svg$/, ".png");
    await writeFile(svgPath, card(c));

    await run("python3", [
      "-c",
      `import cairosvg; cairosvg.svg2png(url=${JSON.stringify(svgPath)}, write_to=${JSON.stringify(png)}, output_width=1200, output_height=630)`,
    ]);
    await run("sips", [
      "-s", "format", "jpeg",
      "-s", "formatOptions", "82",
      png, "--out", c.file,
    ]);

    const { stdout } = await run("stat", ["-f", "%z", c.file]);
    console.log(`  ${c.file} (${stdout.trim()} bytes)`);
  }
}

main();
